import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "@/components/home/dark-mode";
import Navbar from "@/components/home/home-navbar";
import Providers from "@/providers/providers";
import { SyncManager } from "@/components/SyncManager";
import { QueryProvider } from "@/providers/QueryProvider";
import { GlobalTimer } from "@/components/GlobalTImer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Absensi RAD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning>
        <DarkModeProvider>
          <Providers>
            <QueryProvider>
            <SyncManager />
            <main>
              <Navbar />
              {children}
              <GlobalTimer />
            </main>
            </QueryProvider>
          </Providers>
        </DarkModeProvider>
      </body>
    </html>
  );
}
